[env:esp32-s2-saola-1]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200

# Functionality: HomeKit + USB HID
lib_deps = 
	homespan/HomeSpan @ ^1.8.0
	adafruit/Adafruit TinyUSB Library @ ^3.1.0

build_flags = 
	-D ARDUINO_USB_MODE=0
	-D USE_TINYUSB
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-D CORE_DEBUG_LEVEL=1
board_build.partitions = huge_app.csv

